CC=gcc
#INC = -I/ex1 -I/ex2 -I/ex3
CFLAGS=-Wall -g 
OBJS = ex1 ex3 ex4 ex5 ex6 ex7 ex8 ex9 ex10

all: ex1 ex2 ex3 ex4 ex5 ex6 ex7 ex8 ex9 ex10

ex1:
	$(CC) $(CFLAGS) ex1.c -o ex1

ex2: ex1

ex3: 
	$(CC) $(CFLAGS) ex3.c -o ex3

ex4: 
	$(CC) $(CFLAGS) ex4.c -o ex4

ex5:
	$(CC) $(CFLAGS) ex5.c -o ex5


ex6:
	$(CC) $(CFLAGS) ex6.c -o ex6

ex7:
	$(CC) $(CFLAGS) ex7.c -o ex7

ex8:
	$(CC) $(CFLAGS) ex8.c -o ex8

ex9:
	$(CC) $(CFLAGS) ex9.c -o ex9

ex10:
	$(CC) $(CFLAGS) ex10.c -o ex10

clean:
	rm -rf $(OBJS)
